// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package handler

import (
	"net/http"

	"sensor/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/sensors",
				Handler: ListSensorsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sensors",
				Handler: CreateSensorHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/sensors/:name",
				Handler: UpdateSensorHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/sensors/:name",
				Handler: DeleteSensorHandler(serverCtx),
			},
		},
	)
}
