// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package types

type SensorDataRequest struct {
	Name  string  `path:"name"`
	Value int `json:"value"`
}

type SensorDataResponse struct {
	Num    int     `json:"num"`
	Name  string  `json:"name"`
	Value int `json:"value"`
}
